### ISSUE TITLE
Bug - Error en los tests bajo la API 22

### ISSUE THREAD

**Issue by Gerzon-MISO** [Gerzon-MISO/misw4203-ingenieria-de-software-para-aplicaciones-moviles-2021-15#55]
## Error reportado por el Tutor en la ejecución de las pruebas.

He probado con un emulador contando con la API 22 / versión L, sin embargo, se genera el siguiente error: "android.content.res.Resources$NotFoundException: Resource ID #0x7f070088"

**Comment by EdgarLunaG-442** [comment]
Se implementa la imagen noimg.jpg en la carpeta drawable y no unicamente en drawable-24. Esto soluciona el problema para la versión 22 de android.

![image](https://user-images.githubusercontent.com/65874993/142741847-af038c9a-b547-497d-90fc-7cf2008ac3ee.png)
